# Generated by Django 3.2.25 on 2025-10-27 06:55

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

def create_group_and_permissions(apps, schema_editor):
    # Get models
    PcbType = apps.get_model('ModuleTrack', 'PcbType')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Get content type for PcbType
    pcb_type_content_type = ContentType.objects.get_for_model(PcbType)

    # Get permissions for PcbType
    add_permission = Permission.objects.get(codename='add_pcbtype', content_type=pcb_type_content_type.pk)
    change_permission = Permission.objects.get(codename='change_pcbtype', content_type=pcb_type_content_type.pk)
    delete_permission = Permission.objects.get(codename='delete_pcbtype', content_type=pcb_type_content_type.pk)
    view_permission = Permission.objects.get(codename='view_pcbtype', content_type=pcb_type_content_type.pk)

    # Create group
    group, created = Group.objects.get_or_create(name='mng_pcb_type')

    # Assign permissions to group
    group.permissions.add(add_permission, change_permission, delete_permission, view_permission)

def remove_group_and_permissions(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    group = Group.objects.get(name='mng_pcb_type')
    group.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleTrack', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_group_and_permissions, remove_group_and_permissions),
    ]
